export const SUBJECT_TRANSLATIONS: Record<string, string> = {
  我: "I",
  你: "you",
  您: "you",
  他: "he",
  她: "she",
  它: "it",
  我们: "we",
  你们: "you",
  他们: "they",
  她们: "they",
  它们: "they",
  大家: "everyone",
};

export const OBJECT_TRANSLATIONS: Record<string, string> = {
  我: "me",
  你: "you",
  您: "you",
  他: "him",
  她: "her",
  它: "it",
  我们: "us",
  你们: "you",
  他们: "them",
  她们: "them",
  它们: "them",
  中文: "Chinese",
  汉语: "Chinese",
  汉文: "Chinese",
};

export const POSSESSIVE_TRANSLATIONS: Record<string, string> = {
  我: "my",
  你: "your",
  您: "your",
  他: "his",
  她: "her",
  它: "its",
  我们: "our",
  你们: "your",
  他们: "their",
  她们: "their",
  它们: "their",
  这: "this",
  那: "that",
};

export const ENGLISH_POSSESSIVES: Record<string, string> = {
  I: "my",
  you: "your",
  he: "his",
  she: "her",
  it: "its",
  we: "our",
  they: "their",
  everyone: "everyone's",
};

export const TIME_TRANSLATIONS: Record<string, string> = {
  每天: "every day",
  今天: "today",
  明天: "tomorrow",
  昨天: "yesterday",
  现在: "now",
  今年: "this year",
  明年: "next year",
  去年: "last year",
  早上: "in the morning",
  上午: "in the morning",
  中午: "at noon",
  下午: "in the afternoon",
  晚上: "in the evening",
};

export const ADVERB_TRANSLATIONS: Record<string, string> = {
  也: "also",
  都: "all",
  常常: "often",
  经常: "often",
  总是: "always",
  一起: "together",
  正在: "currently",
  真: "really",
  太: "too",
  比较: "quite",
};

export const ADJECTIVE_TRANSLATIONS: Record<string, string> = {
  好: "good",
  高: "tall",
  大: "big",
  小: "small",
  忙: "busy",
  累: "tired",
  漂亮: "pretty",
  高兴: "happy",
  开心: "happy",
  冷: "cold",
  热: "hot",
  快: "fast",
  慢: "slow",
  远: "far",
  近: "near",
  贵: "expensive",
  便宜: "cheap",
  难: "difficult",
  容易: "easy",
  对: "right",
  错: "wrong",
  新: "new",
  老: "old",
  长: "long",
  短: "short",
};

export const QUESTION_WORD_TRANSLATIONS: Record<string, string> = {
  什么: "what",
  谁: "who",
  哪儿: "where",
  哪里: "where",
  怎么: "how",
  为什么: "why",
};

export const LOCATION_QUESTION_WORDS = new Set(["哪儿", "哪里"]);

export const FRONTED_TIME_PHRASES = new Set([
  "today",
  "tomorrow",
  "yesterday",
  "now",
  "this year",
  "next year",
  "last year",
]);

export const AT_LOCATIONS = new Set([
  "school",
  "home",
  "work",
  "the office",
  "the hospital",
  "the library",
  "the bank",
  "the restaurant",
  "the station",
  "the airport",
]);

export const IN_LOCATIONS = new Set([
  "china",
  "beijing",
  "shanghai",
  "japan",
  "america",
  "the classroom",
  "the room",
  "the house",
  "the store",
]);

export const VERB_TRANSLATIONS: Record<string, string> = {
  喜欢: "like",
  想: "want",
  要: "want",
  会: "can",
  去: "go",
  来: "come",
  看: "see",
  吃: "eat",
  喝: "drink",
  学: "study",
  学习: "study",
  说: "speak",
  讲: "speak",
  做: "do",
  买: "buy",
  知道: "know",
  认识: "know",
  叫: "be called",
  住: "live",
  用: "use",
  找: "look for",
  见: "see",
  工作: "work",
  睡觉: "sleep",
  回: "return",
  回家: "go home",
  帮助: "help",
  教: "teach",
  问: "ask",
  回答: "answer",
  打电话: "call",
  给: "give",
  穿: "wear",
  拿: "hold",
  写: "write",
  放: "put",
  开: "open",
  关: "close",
  送: "send",
  带: "bring",
  帮: "help",
  坐: "sit",
  站: "stand",
  等: "wait for",
  让: "let",
  看见: "see",
  看到: "see",
  找到: "find",
  学会: "learn",
  听懂: "understand",
  做完: "finish",
  写完: "finish writing",
  买到: "buy",
  吃完: "finish eating",
  说完: "finish speaking",
};

export const RESULTATIVE_VERB_TRANSLATIONS: Record<string, string> = {
  看见: "see",
  看到: "see",
  找到: "find",
  学会: "learn",
  听懂: "understand",
  做完: "finish",
  写完: "finish writing",
  买到: "buy",
  吃完: "finish eating",
  说完: "finish speaking",
};

export const COMPLEMENT_TRANSLATIONS: Record<
  string,
  { positive?: string; negative?: string }
> = {
  看得到: { positive: "can see" },
  看不到: { negative: "cannot see" },
  看得懂: { positive: "can understand" },
  看不懂: { negative: "cannot understand" },
  听得见: { positive: "can hear" },
  听不见: { negative: "cannot hear" },
  听得懂: { positive: "can understand" },
  听不懂: { negative: "cannot understand" },
  找得到: { positive: "can find" },
  找不到: { negative: "cannot find" },
};

export const DYNAMIC_PASSIVE_PARTICIPLES = new Set([
  "found",
  "caught",
  "seen",
  "hit",
  "hurt",
  "called",
  "invited",
  "stopped",
  "taken",
  "sent",
  "given",
]);

export const SKIPPABLE_TOKENS = new Set([
  "的",
  "了",
  "过",
  "着",
  "吧",
  "呢",
  "啊",
  "呀",
  "啦",
]);

export const MEASURE_WORDS = new Set([
  "个",
  "本",
  "张",
  "只",
  "位",
  "条",
  "杯",
  "碗",
  "块",
  "件",
  "些",
]);
