export const SUBJECT_TRANSLATIONS: Record<string, string> = {
  我: "I",
  你: "you",
  您: "you",
  他: "he",
  她: "she",
  它: "it",
  我们: "we",
  你们: "you",
  他们: "they",
  她们: "they",
  它们: "they",
  大家: "everyone",
};

export const OBJECT_TRANSLATIONS: Record<string, string> = {
  我: "me",
  你: "you",
  您: "you",
  他: "him",
  她: "her",
  它: "it",
  我们: "us",
  你们: "you",
  他们: "them",
  她们: "them",
  它们: "them",
  人: "person",
  书: "book",
  门: "door",
  公司: "company",
  照片: "photo",
  饭: "meal",
  信: "letter",
  时间: "time",
  名字: "name",
  信心: "confidence",
  耐心: "patience",
  办法: "way",
  意思: "meaning",
  希望: "hope",
  音乐: "music",
  问题: "question",
  帮助: "help",
  压力: "pressure",
  麻烦: "trouble",
  事: "matter",
  事情: "matter",
  老师: "teacher",
  学生: "student",
  电影: "movie",
  消息: "message",
  文件: "document",
  报告: "report",
  中文: "Chinese",
  汉语: "Chinese",
  汉文: "Chinese",
  外语: "foreign languages",
  字: "character",
  说法: "expression",
  礼物: "gift",
  东西: "things",
  手机: "cell phone",
  钥匙: "keys",
  黑板: "blackboard",
  窗户: "window",
  门口: "doorway",
  地方: "place",
  活动: "event",
  那边: "there",
  咖啡: "coffee",
  牛奶: "milk",
  味道: "flavor",
  朋友: "friend",
  菜: "dish",
  脸: "face",
  牙: "teeth",
  衣服: "clothing",
  箱子: "box",
};

export const DEMONSTRATIVE_TRANSLATIONS: Record<string, string> = {
  这: "this",
  这个: "this",
  这些: "these",
  那: "that",
  那个: "that",
  那些: "those",
};

export const POSSESSIVE_TRANSLATIONS: Record<string, string> = {
  我: "my",
  你: "your",
  您: "your",
  他: "his",
  她: "her",
  它: "its",
  我们: "our",
  你们: "your",
  他们: "their",
  她们: "their",
  它们: "their",
  这: "this",
  那: "that",
};

export const POSSESSIVE_PRONOUN_TRANSLATIONS: Record<string, string> = {
  my: "mine",
  your: "yours",
  his: "his",
  her: "hers",
  its: "its",
  our: "ours",
  their: "theirs",
  whose: "whose",
};

export const ENGLISH_POSSESSIVES: Record<string, string> = {
  I: "my",
  you: "your",
  he: "his",
  she: "her",
  it: "its",
  we: "our",
  they: "their",
  everyone: "everyone's",
};

export const TIME_TRANSLATIONS: Record<string, string> = {
  每天: "every day",
  今天: "today",
  明天: "tomorrow",
  昨天: "yesterday",
  现在: "now",
  今年: "this year",
  明年: "next year",
  去年: "last year",
  早上: "in the morning",
  上午: "in the morning",
  中午: "at noon",
  下午: "in the afternoon",
  晚上: "in the evening",
};

export const ADVERB_TRANSLATIONS: Record<string, string> = {
  也: "also",
  都: "all",
  还: "still",
  还是: "still",
  已经: "already",
  以前: "before",
  终于: "finally",
  先: "first",
  再: "then",
  更: "more",
  快: "quickly",
  直接: "directly",
  常常: "often",
  经常: "often",
  总是: "always",
  一起: "together",
  正在: "currently",
  真: "really",
  太: "too",
  比较: "quite",
  本来: "originally",
  后来: "later",
  突然: "suddenly",
  临时: "at the last minute",
};

export const SUBJECT_CONTINUATION_CLAUSE_STARTERS = new Set([
  "再",
  "就",
  "还",
  "已经",
  "后来",
  "结果",
  "直到",
  "没",
  "没有",
  "不",
  "只能",
  "直接",
  "为什么",
]);

export const RESULT_CLAUSE_CONNECTORS = new Set(["结果"]);

export const LATER_CLAUSE_CONNECTORS = new Set(["后来"]);

export const UNTIL_CLAUSE_CONNECTORS = new Set(["直到"]);

export const ADJECTIVE_TRANSLATIONS: Record<string, string> = {
  好: "good",
  高: "tall",
  大: "big",
  小: "small",
  忙: "busy",
  累: "tired",
  漂亮: "pretty",
  高兴: "happy",
  开心: "happy",
  冷: "cold",
  热: "hot",
  快: "fast",
  慢: "slow",
  远: "far",
  近: "near",
  贵: "expensive",
  便宜: "cheap",
  方便: "convenient",
  难: "difficult",
  简单: "simple",
  容易: "easy",
  辣: "spicy",
  生气: "angry",
  担心: "worried",
  对: "right",
  错: "wrong",
  新: "new",
  老: "old",
  长: "long",
  晚: "late",
  短: "short",
  空: "free",
  重: "heavy",
};

export const QUESTION_WORD_TRANSLATIONS: Record<string, string> = {
  什么: "what",
  谁: "who",
  哪儿: "where",
  哪里: "where",
  怎么: "how",
  为什么: "why",
};

export const LOCATION_QUESTION_WORDS = new Set(["哪儿", "哪里"]);

export const FRONTED_TIME_PHRASES = new Set([
  "today",
  "tomorrow",
  "yesterday",
  "now",
  "this year",
  "next year",
  "last year",
]);

export const AT_LOCATIONS = new Set([
  "school",
  "home",
  "work",
  "the office",
  "the hospital",
  "the library",
  "the bank",
  "the restaurant",
  "the station",
  "the airport",
]);

export const IN_LOCATIONS = new Set([
  "china",
  "beijing",
  "shanghai",
  "japan",
  "america",
  "the classroom",
  "the room",
  "the house",
  "the store",
]);

export const VERB_TRANSLATIONS: Record<string, string> = {
  喜欢: "like",
  想: "want",
  要: "want",
  会: "can",
  能: "can",
  可以: "can",
  去: "go",
  出去: "go out",
  来: "come",
  下雨: "rain",
  看: "see",
  看起来: "look",
  看书: "read",
  看电影: "watch a movie",
  看电视: "watch TV",
  看懂: "understand",
  懂: "understand",
  写作业: "do homework",
  吃: "eat",
  吃饭: "eat",
  喝: "drink",
  学: "study",
  学习: "study",
  说: "speak",
  说话: "talk",
  听: "listen",
  闻: "smell",
  尝: "taste",
  讲: "speak",
  做: "do",
  数: "count",
  办: "manage",
  买: "buy",
  洗澡: "shower",
  洗衣服: "wash clothes",
  刷牙: "brush",
  洗脸: "wash",
  知道: "know",
  认识: "know",
  认: "recognize",
  叫: "be called",
  住: "live",
  用: "use",
  找: "look for",
  见: "see",
  工作: "work",
  上班: "go to work",
  上大学: "attend university",
  下课: "finish class",
  睡觉: "sleep",
  起床: "get up",
  回: "return",
  回家: "go home",
  帮助: "help",
  教: "teach",
  问: "ask",
  回答: "answer",
  打电话: "call",
  写信: "write",
  做饭: "cook",
  打算: "plan",
  给: "give",
  关上: "close",
  穿: "wear",
  拿: "hold",
  拿出: "take out",
  拿出来: "take out",
  拿进去: "take inside",
  记: "remember",
  写: "write",
  继续: "continue",
  发: "send",
  发消息: "send a message",
  放: "put",
  开: "open",
  开门: "open the door",
  开会: "have a meeting",
  关: "close",
  送: "send",
  送给: "give",
  送出来: "bring out",
  送回去: "send back",
  拍: "take",
  带: "bring",
  帮: "help",
  聊: "chat",
  跑: "run",
  坐: "sit",
  站: "stand",
  走: "go",
  走进去: "walk in",
  等: "wait for",
  告诉: "tell",
  联系: "keep in touch",
  决定: "decide",
  放弃: "give up",
  忘: "forget",
  提醒: "remind",
  带来: "bring",
  改主意: "change one's mind",
  摔倒: "fall",
  迟到: "arrive late",
  准备好: "be ready",
  开始: "start",
  弄明白: "figure out",
  搬: "move",
  搬进去: "carry inside",
  搬出来: "carry out",
  搬回去: "carry back",
  挂: "hang",
  带回去: "take back",
  休息: "rest",
  让: "let",
  参加: "take part in",
  担心: "worry",
  结婚: "get married",
  想象: "imagine",
  打折: "be on sale",
  批评: "criticize",
  骗: "deceive",
  打开: "open",
  开除: "fire",
  到家: "get home",
  下大雨: "rain heavily",
  看见: "see",
  看到: "see",
  找到: "find",
  想好: "figure out",
  买东西: "shop",
  学会: "learn",
  听懂: "understand",
  做完: "finish",
  写完: "finish writing",
  买到: "buy",
  吃完: "finish eating",
  说完: "finish speaking",
};

export const MODAL_TRANSLATIONS: Record<string, string> = {
  会: "can",
  能: "can",
  可以: "can",
};

export const DESIDERATIVE_TRANSLATIONS: Record<string, string> = {
  想: "want",
  要: "want",
};

export const RESULTATIVE_VERB_TRANSLATIONS: Record<string, string> = {
  看见: "see",
  看到: "see",
  找到: "find",
  学会: "learn",
  记住: "remember",
  听见: "hear",
  听懂: "understand",
  听到: "hear",
  看懂: "understand",
  吹开: "blow open",
  拿进去: "take inside",
  拿出来: "take out",
  搬进去: "carry inside",
  搬出来: "carry out",
  关上: "close",
  带回去: "take back",
  搬回去: "carry back",
  送出来: "bring out",
  送回去: "send back",
  做好: "do well",
  做完: "finish",
  写完: "finish writing",
  买到: "buy",
  吃完: "finish eating",
  说完: "finish speaking",
};

export type ComplementMeaningCategory =
  | "ability"
  | "resultative"
  | "perception"
  | "comprehension"
  | "feasibility";

export type ComplementMeaning = {
  category: ComplementMeaningCategory;
  baseVerb: string;
  complement: string;
  positive: string;
  negative: string;
  object?: string;
  positiveQuestion?: string;
  negativeQuestion?: string;
};

export const COMPLEMENT_MEANINGS: Record<string, ComplementMeaning> = {
  看得懂: {
    category: "comprehension",
    baseVerb: "看",
    complement: "懂",
    positive: "can read and understand it",
    negative: "cannot understand it",
    object: "it",
    positiveQuestion: "read and understand it",
    negativeQuestion: "understand it",
  },
  看不懂: {
    category: "comprehension",
    baseVerb: "看",
    complement: "懂",
    positive: "can understand it",
    negative: "cannot understand it",
    object: "it",
    positiveQuestion: "understand it",
    negativeQuestion: "understand it",
  },
  看得清楚: {
    category: "perception",
    baseVerb: "看",
    complement: "清楚",
    positive: "can see it clearly",
    negative: "cannot see it clearly",
    object: "it",
    positiveQuestion: "see it clearly",
    negativeQuestion: "see it clearly",
  },
  看得清: {
    category: "perception",
    baseVerb: "看",
    complement: "清",
    positive: "can see it clearly",
    negative: "cannot see it clearly",
    object: "it",
    positiveQuestion: "see it clearly",
    negativeQuestion: "see it clearly",
  },
  看不清: {
    category: "perception",
    baseVerb: "看",
    complement: "清",
    positive: "can see it clearly",
    negative: "cannot see it clearly",
    object: "it",
    positiveQuestion: "see it clearly",
    negativeQuestion: "see it clearly",
  },
  看不清楚: {
    category: "perception",
    baseVerb: "看",
    complement: "清楚",
    positive: "can see it clearly",
    negative: "cannot see it clearly",
    object: "it",
    positiveQuestion: "see it clearly",
    negativeQuestion: "see it clearly",
  },
  看得出来: {
    category: "perception",
    baseVerb: "看",
    complement: "出来",
    positive: "can tell that it",
    negative: "cannot tell that it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell that it",
  },
  看不出来: {
    category: "perception",
    baseVerb: "看",
    complement: "出来",
    positive: "can tell that it",
    negative: "cannot tell that it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell that it",
  },
  听得见: {
    category: "perception",
    baseVerb: "听",
    complement: "见",
    positive: "can hear it",
    negative: "cannot hear it",
    object: "it",
    positiveQuestion: "hear it",
    negativeQuestion: "hear it",
  },
  听不见: {
    category: "perception",
    baseVerb: "听",
    complement: "见",
    positive: "can hear it",
    negative: "cannot hear it",
    object: "it",
    positiveQuestion: "hear it",
    negativeQuestion: "hear it",
  },
  听得出来: {
    category: "perception",
    baseVerb: "听",
    complement: "出来",
    positive: "can tell that it",
    negative: "cannot tell that it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell that it",
  },
  听不出来: {
    category: "perception",
    baseVerb: "听",
    complement: "出来",
    positive: "can tell that it",
    negative: "cannot tell that it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell that it",
  },
  闻得出来: {
    category: "perception",
    baseVerb: "闻",
    complement: "出来",
    positive: "can recognize it",
    negative: "cannot recognize it",
    object: "it",
    positiveQuestion: "recognize it",
    negativeQuestion: "recognize it",
  },
  闻不出来: {
    category: "perception",
    baseVerb: "闻",
    complement: "出来",
    positive: "can recognize it",
    negative: "cannot recognize it",
    object: "it",
    positiveQuestion: "recognize it",
    negativeQuestion: "recognize it",
  },
  闻得出: {
    category: "perception",
    baseVerb: "闻",
    complement: "出",
    positive: "can tell that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell it",
  },
  闻不出: {
    category: "perception",
    baseVerb: "闻",
    complement: "出",
    positive: "can tell that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell it",
  },
  尝得出来: {
    category: "perception",
    baseVerb: "尝",
    complement: "出来",
    positive: "can recognize it",
    negative: "cannot recognize it",
    object: "it",
    positiveQuestion: "recognize it",
    negativeQuestion: "recognize it",
  },
  尝不出来: {
    category: "perception",
    baseVerb: "尝",
    complement: "出来",
    positive: "can recognize it",
    negative: "cannot recognize it",
    object: "it",
    positiveQuestion: "recognize it",
    negativeQuestion: "recognize it",
  },
  听得清: {
    category: "perception",
    baseVerb: "听",
    complement: "清",
    positive: "can hear it clearly",
    negative: "cannot hear it clearly",
    object: "it",
    positiveQuestion: "hear it clearly",
    negativeQuestion: "hear it clearly",
  },
  听不清: {
    category: "perception",
    baseVerb: "听",
    complement: "清",
    positive: "can hear it clearly",
    negative: "cannot hear it clearly",
    object: "it",
    positiveQuestion: "hear it clearly",
    negativeQuestion: "hear it clearly",
  },
  听得清楚: {
    category: "perception",
    baseVerb: "听",
    complement: "清楚",
    positive: "can hear it clearly",
    negative: "cannot hear it clearly",
    object: "it",
    positiveQuestion: "hear it clearly",
    negativeQuestion: "hear it clearly",
  },
  听不清楚: {
    category: "perception",
    baseVerb: "听",
    complement: "清楚",
    positive: "can hear it clearly",
    negative: "cannot hear it clearly",
    object: "it",
    positiveQuestion: "hear it clearly",
    negativeQuestion: "hear it clearly",
  },
  讲得清: {
    category: "ability",
    baseVerb: "讲",
    complement: "清",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  讲不清: {
    category: "ability",
    baseVerb: "讲",
    complement: "清",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  讲得清楚: {
    category: "ability",
    baseVerb: "讲",
    complement: "清楚",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  讲不清楚: {
    category: "ability",
    baseVerb: "讲",
    complement: "清楚",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  听得明白: {
    category: "comprehension",
    baseVerb: "听",
    complement: "明白",
    positive: "can understand it clearly",
    negative: "cannot understand it clearly",
    object: "it",
    positiveQuestion: "understand it clearly",
    negativeQuestion: "understand it clearly",
  },
  听不明白: {
    category: "comprehension",
    baseVerb: "听",
    complement: "明白",
    positive: "can understand it clearly",
    negative: "cannot understand it clearly",
    object: "it",
    positiveQuestion: "understand it clearly",
    negativeQuestion: "understand it clearly",
  },
  听得懂: {
    category: "comprehension",
    baseVerb: "听",
    complement: "懂",
    positive: "can understand it",
    negative: "cannot understand it",
    object: "it",
    positiveQuestion: "understand it",
    negativeQuestion: "understand it",
  },
  听不懂: {
    category: "comprehension",
    baseVerb: "听",
    complement: "懂",
    positive: "can understand it",
    negative: "cannot understand it",
    object: "it",
    positiveQuestion: "understand it",
    negativeQuestion: "understand it",
  },
  看得明白: {
    category: "comprehension",
    baseVerb: "看",
    complement: "明白",
    positive: "can understand it clearly",
    negative: "cannot understand it clearly",
    object: "it",
    positiveQuestion: "understand it clearly",
    negativeQuestion: "understand it clearly",
  },
  看不明白: {
    category: "comprehension",
    baseVerb: "看",
    complement: "明白",
    positive: "can understand it clearly",
    negative: "cannot understand it clearly",
    object: "it",
    positiveQuestion: "understand it clearly",
    negativeQuestion: "understand it clearly",
  },
  闻得到: {
    category: "perception",
    baseVerb: "闻",
    complement: "到",
    positive: "can smell it",
    negative: "cannot smell it",
    object: "it",
    positiveQuestion: "smell it",
    negativeQuestion: "smell it",
  },
  闻不到: {
    category: "perception",
    baseVerb: "闻",
    complement: "到",
    positive: "can smell it",
    negative: "cannot smell it",
    object: "it",
    positiveQuestion: "smell it",
    negativeQuestion: "smell it",
  },
  尝得出: {
    category: "perception",
    baseVerb: "尝",
    complement: "出",
    positive: "can taste that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "taste that it",
    negativeQuestion: "tell it",
  },
  尝不出: {
    category: "perception",
    baseVerb: "尝",
    complement: "出",
    positive: "can taste that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "taste that it",
    negativeQuestion: "tell it",
  },
  吃得出: {
    category: "perception",
    baseVerb: "吃",
    complement: "出",
    positive: "can tell that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell it",
  },
  吃不出: {
    category: "perception",
    baseVerb: "吃",
    complement: "出",
    positive: "can tell that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell it",
  },
  吃得准: {
    category: "perception",
    baseVerb: "吃",
    complement: "准",
    positive: "can tell that it",
    negative: "cannot tell whether it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell whether it",
  },
  吃不准: {
    category: "perception",
    baseVerb: "吃",
    complement: "准",
    positive: "can tell that it",
    negative: "cannot tell whether it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell whether it",
  },
  听得准: {
    category: "perception",
    baseVerb: "听",
    complement: "准",
    positive: "can hear it accurately",
    negative: "cannot hear it clearly",
    object: "it",
    positiveQuestion: "hear it accurately",
    negativeQuestion: "hear it clearly",
  },
  听不准: {
    category: "perception",
    baseVerb: "听",
    complement: "准",
    positive: "can hear it accurately",
    negative: "cannot hear it clearly",
    object: "it",
    positiveQuestion: "hear it accurately",
    negativeQuestion: "hear it clearly",
  },
  认得清: {
    category: "ability",
    baseVerb: "认",
    complement: "清",
    positive: "can clearly recognize it",
    negative: "cannot clearly recognize it",
    object: "it",
    positiveQuestion: "clearly recognize it",
    negativeQuestion: "clearly recognize it",
  },
  认不清: {
    category: "ability",
    baseVerb: "认",
    complement: "清",
    positive: "can clearly recognize it",
    negative: "cannot clearly recognize it",
    object: "it",
    positiveQuestion: "clearly recognize it",
    negativeQuestion: "clearly recognize it",
  },
  看得准: {
    category: "perception",
    baseVerb: "看",
    complement: "准",
    positive: "can correctly judge it",
    negative: "cannot accurately judge it",
    object: "it",
    positiveQuestion: "correctly judge it",
    negativeQuestion: "accurately judge it",
  },
  看不准: {
    category: "perception",
    baseVerb: "看",
    complement: "准",
    positive: "can correctly judge it",
    negative: "cannot accurately judge it",
    object: "it",
    positiveQuestion: "correctly judge it",
    negativeQuestion: "accurately judge it",
  },
  说得准: {
    category: "ability",
    baseVerb: "说",
    complement: "准",
    positive: "speak accurately",
    negative: "cannot say for sure",
    positiveQuestion: "speak accurately",
    negativeQuestion: "say for sure",
  },
  说不准: {
    category: "ability",
    baseVerb: "说",
    complement: "准",
    positive: "speak accurately",
    negative: "cannot say for sure",
    positiveQuestion: "speak accurately",
    negativeQuestion: "say for sure",
  },
  说得出: {
    category: "ability",
    baseVerb: "说",
    complement: "出",
    positive: "can say it",
    negative: "cannot say it",
    object: "it",
    positiveQuestion: "say it",
    negativeQuestion: "say it",
  },
  说不出: {
    category: "ability",
    baseVerb: "说",
    complement: "出",
    positive: "can say it",
    negative: "cannot say it",
    object: "it",
    positiveQuestion: "say it",
    negativeQuestion: "say it",
  },
  说得清: {
    category: "ability",
    baseVerb: "说",
    complement: "清",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  说不清: {
    category: "ability",
    baseVerb: "说",
    complement: "清",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  说得清楚: {
    category: "ability",
    baseVerb: "说",
    complement: "清楚",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  说不清楚: {
    category: "ability",
    baseVerb: "说",
    complement: "清楚",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  说得明白: {
    category: "ability",
    baseVerb: "说",
    complement: "明白",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  说不明白: {
    category: "ability",
    baseVerb: "说",
    complement: "明白",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  猜得准: {
    category: "ability",
    baseVerb: "猜",
    complement: "准",
    positive: "can correctly guess it",
    negative: "cannot accurately guess it",
    object: "it",
    positiveQuestion: "correctly guess it",
    negativeQuestion: "accurately guess it",
  },
  猜不准: {
    category: "ability",
    baseVerb: "猜",
    complement: "准",
    positive: "can correctly guess it",
    negative: "cannot accurately guess it",
    object: "it",
    positiveQuestion: "correctly guess it",
    negativeQuestion: "accurately guess it",
  },
  认得准: {
    category: "ability",
    baseVerb: "认",
    complement: "准",
    positive: "can accurately recognize it",
    negative: "cannot accurately recognize it",
    object: "it",
    positiveQuestion: "accurately recognize it",
    negativeQuestion: "accurately recognize it",
  },
  认不准: {
    category: "ability",
    baseVerb: "认",
    complement: "准",
    positive: "can accurately recognize it",
    negative: "cannot accurately recognize it",
    object: "it",
    positiveQuestion: "accurately recognize it",
    negativeQuestion: "accurately recognize it",
  },
  认得出: {
    category: "ability",
    baseVerb: "认",
    complement: "出",
    positive: "can recognize it",
    negative: "cannot recognize it",
    object: "it",
    positiveQuestion: "recognize it",
    negativeQuestion: "recognize it",
  },
  认不出: {
    category: "ability",
    baseVerb: "认",
    complement: "出",
    positive: "can recognize it",
    negative: "cannot recognize it",
    object: "it",
    positiveQuestion: "recognize it",
    negativeQuestion: "recognize it",
  },
  看得出: {
    category: "perception",
    baseVerb: "看",
    complement: "出",
    positive: "can tell that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell it",
  },
  看不出: {
    category: "perception",
    baseVerb: "看",
    complement: "出",
    positive: "can tell that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell it",
  },
  听得出: {
    category: "perception",
    baseVerb: "听",
    complement: "出",
    positive: "can tell that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell it",
  },
  听不出: {
    category: "perception",
    baseVerb: "听",
    complement: "出",
    positive: "can tell that it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell that it",
    negativeQuestion: "tell it",
  },
  摸得出: {
    category: "perception",
    baseVerb: "摸",
    complement: "出",
    positive: "can tell it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell it",
    negativeQuestion: "tell it",
  },
  摸不出: {
    category: "perception",
    baseVerb: "摸",
    complement: "出",
    positive: "can tell it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell it",
    negativeQuestion: "tell it",
  },
  分得出: {
    category: "ability",
    baseVerb: "分",
    complement: "出",
    positive: "can tell it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell it",
    negativeQuestion: "tell it",
  },
  分不出: {
    category: "ability",
    baseVerb: "分",
    complement: "出",
    positive: "can tell it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell it",
    negativeQuestion: "tell it",
  },
  分得准: {
    category: "ability",
    baseVerb: "分",
    complement: "准",
    positive: "can accurately distinguish it",
    negative: "cannot accurately distinguish it",
    object: "it",
    positiveQuestion: "accurately distinguish it",
    negativeQuestion: "accurately distinguish it",
  },
  分不准: {
    category: "ability",
    baseVerb: "分",
    complement: "准",
    positive: "can accurately distinguish it",
    negative: "cannot accurately distinguish it",
    object: "it",
    positiveQuestion: "accurately distinguish it",
    negativeQuestion: "accurately distinguish it",
  },
  叫得出: {
    category: "ability",
    baseVerb: "叫",
    complement: "出",
    positive: "can say it",
    negative: "cannot say it",
    object: "it",
    positiveQuestion: "say it",
    negativeQuestion: "say it",
  },
  叫不出: {
    category: "ability",
    baseVerb: "叫",
    complement: "出",
    positive: "can say it",
    negative: "cannot say it",
    object: "it",
    positiveQuestion: "say it",
    negativeQuestion: "say it",
  },
  想得出: {
    category: "ability",
    baseVerb: "想",
    complement: "出",
    positive: "can think of it",
    negative: "cannot think of it",
    object: "it",
    positiveQuestion: "think of it",
    negativeQuestion: "think of it",
  },
  想不出: {
    category: "ability",
    baseVerb: "想",
    complement: "出",
    positive: "can think of it",
    negative: "cannot think of it",
    object: "it",
    positiveQuestion: "think of it",
    negativeQuestion: "think of it",
  },
  拿得准: {
    category: "ability",
    baseVerb: "拿",
    complement: "准",
    positive: "am confident about it",
    negative: "am not sure about it",
    object: "it",
    positiveQuestion: "be confident about it",
    negativeQuestion: "be sure about it",
  },
  拿不准: {
    category: "ability",
    baseVerb: "拿",
    complement: "准",
    positive: "am confident about it",
    negative: "am not sure about it",
    object: "it",
    positiveQuestion: "be confident about it",
    negativeQuestion: "be sure about it",
  },
  定得准: {
    category: "ability",
    baseVerb: "定",
    complement: "准",
    positive: "can accurately judge it",
    negative: "cannot tell for sure it",
    object: "it",
    positiveQuestion: "accurately judge it",
    negativeQuestion: "tell for sure it",
  },
  定不准: {
    category: "ability",
    baseVerb: "定",
    complement: "准",
    positive: "can accurately judge it",
    negative: "cannot tell for sure it",
    object: "it",
    positiveQuestion: "accurately judge it",
    negativeQuestion: "tell for sure it",
  },
  找得到: {
    category: "ability",
    baseVerb: "找",
    complement: "到",
    positive: "can find it",
    negative: "cannot find it",
    object: "it",
    positiveQuestion: "find it",
    negativeQuestion: "find it",
  },
  找不到: {
    category: "ability",
    baseVerb: "找",
    complement: "到",
    positive: "can find it",
    negative: "cannot find it",
    object: "it",
    positiveQuestion: "find it",
    negativeQuestion: "find it",
  },
  找得着: {
    category: "ability",
    baseVerb: "找",
    complement: "着",
    positive: "can find it",
    negative: "cannot find it",
    object: "it",
    positiveQuestion: "find it",
    negativeQuestion: "find it",
  },
  找不着: {
    category: "ability",
    baseVerb: "找",
    complement: "着",
    positive: "can find it",
    negative: "cannot find it",
    object: "it",
    positiveQuestion: "find it",
    negativeQuestion: "find it",
  },
  分得清: {
    category: "ability",
    baseVerb: "分",
    complement: "清",
    positive: "can tell it apart",
    negative: "cannot tell it apart",
    object: "it",
    positiveQuestion: "tell it apart",
    negativeQuestion: "tell it apart",
  },
  分不清: {
    category: "ability",
    baseVerb: "分",
    complement: "清",
    positive: "can tell it apart",
    negative: "cannot tell it apart",
    object: "it",
    positiveQuestion: "tell it apart",
    negativeQuestion: "tell it apart",
  },
  分得清楚: {
    category: "ability",
    baseVerb: "分",
    complement: "清楚",
    positive: "can clearly distinguish it",
    negative: "cannot clearly distinguish it",
    object: "it",
    positiveQuestion: "clearly distinguish it",
    negativeQuestion: "clearly distinguish it",
  },
  分不清楚: {
    category: "ability",
    baseVerb: "分",
    complement: "清楚",
    positive: "can clearly distinguish it",
    negative: "cannot clearly distinguish it",
    object: "it",
    positiveQuestion: "clearly distinguish it",
    negativeQuestion: "clearly distinguish it",
  },
  分得出来: {
    category: "ability",
    baseVerb: "分",
    complement: "出来",
    positive: "can tell it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell it",
    negativeQuestion: "tell it",
  },
  分不出来: {
    category: "ability",
    baseVerb: "分",
    complement: "出来",
    positive: "can tell it",
    negative: "cannot tell it",
    object: "it",
    positiveQuestion: "tell it",
    negativeQuestion: "tell it",
  },
  认得清楚: {
    category: "ability",
    baseVerb: "认",
    complement: "清楚",
    positive: "can clearly recognize it",
    negative: "cannot clearly recognize it",
    object: "it",
    positiveQuestion: "clearly recognize it",
    negativeQuestion: "clearly recognize it",
  },
  认不清楚: {
    category: "ability",
    baseVerb: "认",
    complement: "清楚",
    positive: "can clearly recognize it",
    negative: "cannot clearly recognize it",
    object: "it",
    positiveQuestion: "clearly recognize it",
    negativeQuestion: "clearly recognize it",
  },
  讲得明白: {
    category: "ability",
    baseVerb: "讲",
    complement: "明白",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  讲不明白: {
    category: "ability",
    baseVerb: "讲",
    complement: "明白",
    positive: "can explain it clearly",
    negative: "cannot explain it clearly",
    object: "it",
    positiveQuestion: "explain it clearly",
    negativeQuestion: "explain it clearly",
  },
  讲得懂: {
    category: "ability",
    baseVerb: "讲",
    complement: "懂",
    positive: "can explain it understandably",
    negative: "cannot explain it clearly enough",
    object: "it",
    positiveQuestion: "explain it understandably",
    negativeQuestion: "explain it clearly enough",
  },
  讲不懂: {
    category: "ability",
    baseVerb: "讲",
    complement: "懂",
    positive: "can explain it understandably",
    negative: "cannot explain it clearly enough",
    object: "it",
    positiveQuestion: "explain it understandably",
    negativeQuestion: "explain it clearly enough",
  },
  认得出来: {
    category: "ability",
    baseVerb: "认",
    complement: "出来",
    positive: "can recognize it",
    negative: "cannot recognize it",
    object: "it",
    positiveQuestion: "recognize it",
    negativeQuestion: "recognize it",
  },
  认不出来: {
    category: "ability",
    baseVerb: "认",
    complement: "出来",
    positive: "can recognize it",
    negative: "cannot recognize it",
    object: "it",
    positiveQuestion: "recognize it",
    negativeQuestion: "recognize it",
  },
  想得起来: {
    category: "ability",
    baseVerb: "想",
    complement: "起来",
    positive: "can remember it",
    negative: "cannot remember it",
    object: "it",
    positiveQuestion: "remember it",
    negativeQuestion: "remember it",
  },
  想不起来: {
    category: "ability",
    baseVerb: "想",
    complement: "起来",
    positive: "can remember it",
    negative: "cannot remember it",
    object: "it",
    positiveQuestion: "remember it",
    negativeQuestion: "remember it",
  },
  做得到: {
    category: "ability",
    baseVerb: "做",
    complement: "到",
    positive: "can do it",
    negative: "cannot do it",
    object: "it",
    positiveQuestion: "do it",
    negativeQuestion: "do it",
  },
  做不到: {
    category: "ability",
    baseVerb: "做",
    complement: "到",
    positive: "can do it",
    negative: "cannot do it",
    object: "it",
    positiveQuestion: "do it",
    negativeQuestion: "do it",
  },
  办得到: {
    category: "ability",
    baseVerb: "办",
    complement: "到",
    positive: "can manage it",
    negative: "cannot manage it",
    object: "it",
    positiveQuestion: "manage it",
    negativeQuestion: "manage it",
  },
  办不到: {
    category: "ability",
    baseVerb: "办",
    complement: "到",
    positive: "can manage it",
    negative: "cannot manage it",
    object: "it",
    positiveQuestion: "manage it",
    negativeQuestion: "manage it",
  },
  学得会: {
    category: "ability",
    baseVerb: "学",
    complement: "会",
    positive: "can learn it",
    negative: "cannot learn it",
    object: "it",
    positiveQuestion: "learn it",
    negativeQuestion: "learn it",
  },
  学不会: {
    category: "ability",
    baseVerb: "学",
    complement: "会",
    positive: "can learn it",
    negative: "cannot learn it",
    object: "it",
    positiveQuestion: "learn it",
    negativeQuestion: "learn it",
  },
  记得住: {
    category: "ability",
    baseVerb: "记",
    complement: "住",
    positive: "can remember it",
    negative: "cannot remember it",
    object: "it",
    positiveQuestion: "remember it",
    negativeQuestion: "remember it",
  },
  记不住: {
    category: "ability",
    baseVerb: "记",
    complement: "住",
    positive: "can remember it",
    negative: "cannot remember it",
    object: "it",
    positiveQuestion: "remember it",
    negativeQuestion: "remember it",
  },
  打得开: {
    category: "ability",
    baseVerb: "打",
    complement: "开",
    positive: "can open it",
    negative: "cannot open it",
    object: "it",
    positiveQuestion: "open it",
    negativeQuestion: "open it",
  },
  打不开: {
    category: "ability",
    baseVerb: "打",
    complement: "开",
    positive: "can open it",
    negative: "cannot open it",
    object: "it",
    positiveQuestion: "open it",
    negativeQuestion: "open it",
  },
  来得及: {
    category: "feasibility",
    baseVerb: "来",
    complement: "及",
    positive: "can make it in time",
    negative: "cannot make it in time",
    object: "it",
    positiveQuestion: "make it in time",
    negativeQuestion: "make it in time",
  },
  来不及: {
    category: "feasibility",
    baseVerb: "来",
    complement: "及",
    positive: "can make it in time",
    negative: "cannot make it in time",
    object: "it",
    positiveQuestion: "make it in time",
    negativeQuestion: "make it in time",
  },
  穿不上: {
    category: "ability",
    baseVerb: "穿",
    complement: "上",
    positive: "can put it on",
    negative: "cannot put it on",
    object: "it",
    positiveQuestion: "put it on",
    negativeQuestion: "put it on",
  },
  搬不动: {
    category: "ability",
    baseVerb: "搬",
    complement: "动",
    positive: "can move it",
    negative: "cannot move it",
    object: "it",
    positiveQuestion: "move it",
    negativeQuestion: "move it",
  },
};

export const COMPLEMENT_TRANSLATIONS: Record<
  string,
  { positive?: string; negative?: string }
> = Object.fromEntries(
  Object.entries(COMPLEMENT_MEANINGS).map(([key, value]) => [
    key,
    {
      positive: key.includes("得") ? value.positive : undefined,
      negative: key.includes("不") ? value.negative : undefined,
    },
  ]),
);

export const DYNAMIC_PASSIVE_PARTICIPLES = new Set([
  "found",
  "caught",
  "seen",
  "hit",
  "hurt",
  "called",
  "invited",
  "stopped",
  "taken",
  "sent",
  "given",
]);

export const PROGRESSIVE_MARKERS = new Set(["在", "正在"]);

export const COUNTRY_ADJECTIVE_TRANSLATIONS: Record<string, string> = {
  中国: "Chinese",
};

export const LEXICALIZED_EXPRESSION_TRANSLATIONS: Record<string, string> = {
  你好: "Hello.",
  您好: "Hello.",
  你好吗: "How are you?",
  您好吗: "How are you?",
  你怎么样: "How are you?",
  您怎么样: "How are you?",
  最近怎么样: "How have you been lately?",
  早上好: "Good morning.",
  晚上好: "Good evening.",
  晚安: "Good night.",
  谢谢: "Thank you.",
  不客气: "You're welcome.",
  对不起: "I'm sorry.",
  没关系: "It's okay.",
  再见: "Goodbye.",
  你吃了吗: "Have you eaten?",
  没问题: "No problem.",
  没办法: "There's no way around it.",
  原来如此: "I see.",
  怪不得: "No wonder.",
  真的假的: "Really?",
  太好了: "That's great!",
  好吧: "All right.",
  行吧: "All right.",
  那就这样吧: "All right, let's leave it at that.",
  我呢: "What about me?",
  你呢: "What about you?",
  可以: "Sure.",
};

export const NEGATIVE_IMPERATIVE_MARKERS = new Set(["不要", "别"]);

export const IMPERATIVE_POLITENESS_MARKERS = new Set(["请"]);

export const IMPERATIVE_ADVERB_WORDS = new Set(["快"]);

export const SKIPPABLE_TOKENS = new Set([
  "的",
  "了",
  "过",
  "着",
  "吧",
  "呢",
  "啊",
  "呀",
  "啦",
]);

export const MEASURE_WORDS = new Set([
  "家",
  "个",
  "本",
  "部",
  "张",
  "只",
  "位",
  "条",
  "杯",
  "碗",
  "块",
  "件",
  "段",
  "些",
]);

export const NUMBER_TRANSLATIONS: Record<string, string> = {
  一: "one",
  几: "a few",
  二: "two",
  两: "two",
  三: "three",
  四: "four",
  五: "five",
  六: "six",
  七: "seven",
  八: "eight",
  九: "nine",
  十: "ten",
};

export const NOUN_TRANSLATIONS: Record<string, string> = {
  人: "person",
  书: "book",
  中文: "Chinese",
  汉语: "Chinese",
  汉文: "Chinese",
  外语: "foreign languages",
  文章: "article",
  课文: "text",
  门: "door",
  朋友: "friend",
  公司: "company",
  照片: "photo",
  电影: "movie",
  菜: "dish",
  饭: "meal",
  脸: "face",
  牙: "teeth",
  信: "letter",
  时间: "time",
  名字: "name",
  信心: "confidence",
  耐心: "patience",
  办法: "way",
  意思: "meaning",
  希望: "hope",
  音乐: "music",
  文件: "document",
  报告: "report",
  练习: "exercises",
  消息: "message",
  问题: "question",
  北京: "Beijing",
  中国: "China",
  事: "matter",
  事情: "matter",
  哥哥: "older brother",
  老师: "teacher",
  学生: "student",
  姐姐: "older sister",
  字: "character",
  说法: "expression",
  礼物: "gift",
  东西: "things",
  作业: "homework",
  手机: "cell phone",
  钥匙: "keys",
  黑板: "blackboard",
  窗户: "window",
  门口: "doorway",
  地方: "place",
  店: "store",
  活动: "event",
  那边: "there",
  天气预报: "weather forecast",
  衣服: "clothing",
  箱子: "box",
  空: "time",
};
