export const SUBJECT_TRANSLATIONS: Record<string, string> = {
  我: "I",
  你: "you",
  您: "you",
  他: "he",
  她: "she",
  它: "it",
  我们: "we",
  你们: "you",
  他们: "they",
  她们: "they",
  它们: "they",
  大家: "everyone",
};

export const OBJECT_TRANSLATIONS: Record<string, string> = {
  我: "me",
  你: "you",
  您: "you",
  他: "him",
  她: "her",
  它: "it",
  我们: "us",
  你们: "you",
  他们: "them",
  她们: "them",
  它们: "them",
  人: "person",
  书: "book",
  门: "door",
  公司: "company",
  照片: "photo",
  饭: "meal",
  信: "letter",
  时间: "time",
  名字: "name",
  音乐: "music",
  问题: "question",
  事: "matter",
  事情: "matter",
  老师: "teacher",
  学生: "student",
  中文: "Chinese",
  汉语: "Chinese",
  汉文: "Chinese",
};

export const DEMONSTRATIVE_TRANSLATIONS: Record<string, string> = {
  这: "this",
  这个: "this",
  这些: "these",
  那: "that",
  那个: "that",
  那些: "those",
};

export const POSSESSIVE_TRANSLATIONS: Record<string, string> = {
  我: "my",
  你: "your",
  您: "your",
  他: "his",
  她: "her",
  它: "its",
  我们: "our",
  你们: "your",
  他们: "their",
  她们: "their",
  它们: "their",
  这: "this",
  那: "that",
};

export const POSSESSIVE_PRONOUN_TRANSLATIONS: Record<string, string> = {
  my: "mine",
  your: "yours",
  his: "his",
  her: "hers",
  its: "its",
  our: "ours",
  their: "theirs",
  whose: "whose",
};

export const ENGLISH_POSSESSIVES: Record<string, string> = {
  I: "my",
  you: "your",
  he: "his",
  she: "her",
  it: "its",
  we: "our",
  they: "their",
  everyone: "everyone's",
};

export const TIME_TRANSLATIONS: Record<string, string> = {
  每天: "every day",
  今天: "today",
  明天: "tomorrow",
  昨天: "yesterday",
  现在: "now",
  今年: "this year",
  明年: "next year",
  去年: "last year",
  早上: "in the morning",
  上午: "in the morning",
  中午: "at noon",
  下午: "in the afternoon",
  晚上: "in the evening",
};

export const ADVERB_TRANSLATIONS: Record<string, string> = {
  也: "also",
  都: "all",
  还: "still",
  先: "first",
  再: "then",
  快: "quickly",
  常常: "often",
  经常: "often",
  总是: "always",
  一起: "together",
  正在: "currently",
  真: "really",
  太: "too",
  比较: "quite",
};

export const ADJECTIVE_TRANSLATIONS: Record<string, string> = {
  好: "good",
  高: "tall",
  大: "big",
  小: "small",
  忙: "busy",
  累: "tired",
  漂亮: "pretty",
  高兴: "happy",
  开心: "happy",
  冷: "cold",
  热: "hot",
  快: "fast",
  慢: "slow",
  远: "far",
  近: "near",
  贵: "expensive",
  便宜: "cheap",
  难: "difficult",
  容易: "easy",
  对: "right",
  错: "wrong",
  新: "new",
  老: "old",
  长: "long",
  晚: "late",
  短: "short",
};

export const QUESTION_WORD_TRANSLATIONS: Record<string, string> = {
  什么: "what",
  谁: "who",
  哪儿: "where",
  哪里: "where",
  怎么: "how",
  为什么: "why",
};

export const LOCATION_QUESTION_WORDS = new Set(["哪儿", "哪里"]);

export const FRONTED_TIME_PHRASES = new Set([
  "today",
  "tomorrow",
  "yesterday",
  "now",
  "this year",
  "next year",
  "last year",
]);

export const AT_LOCATIONS = new Set([
  "school",
  "home",
  "work",
  "the office",
  "the hospital",
  "the library",
  "the bank",
  "the restaurant",
  "the station",
  "the airport",
]);

export const IN_LOCATIONS = new Set([
  "china",
  "beijing",
  "shanghai",
  "japan",
  "america",
  "the classroom",
  "the room",
  "the house",
  "the store",
]);

export const VERB_TRANSLATIONS: Record<string, string> = {
  喜欢: "like",
  想: "want",
  要: "want",
  会: "can",
  能: "can",
  可以: "can",
  去: "go",
  来: "come",
  下雨: "rain",
  看: "see",
  看书: "read",
  吃: "eat",
  吃饭: "eat",
  喝: "drink",
  学: "study",
  学习: "study",
  说: "speak",
  说话: "talk",
  听: "listen",
  讲: "speak",
  做: "do",
  办: "manage",
  买: "buy",
  洗澡: "shower",
  知道: "know",
  认识: "know",
  叫: "be called",
  住: "live",
  用: "use",
  找: "look for",
  见: "see",
  工作: "work",
  睡觉: "sleep",
  回: "return",
  回家: "go home",
  帮助: "help",
  教: "teach",
  问: "ask",
  回答: "answer",
  打电话: "call",
  写信: "write",
  做饭: "cook",
  给: "give",
  穿: "wear",
  拿: "hold",
  记: "remember",
  写: "write",
  放: "put",
  开: "open",
  关: "close",
  送: "send",
  带: "bring",
  帮: "help",
  坐: "sit",
  站: "stand",
  走: "go",
  等: "wait for",
  让: "let",
  担心: "worry",
  批评: "criticize",
  骗: "deceive",
  打开: "open",
  开除: "fire",
  看见: "see",
  看到: "see",
  找到: "find",
  想好: "figure out",
  学会: "learn",
  听懂: "understand",
  做完: "finish",
  写完: "finish writing",
  买到: "buy",
  吃完: "finish eating",
  说完: "finish speaking",
};

export const MODAL_TRANSLATIONS: Record<string, string> = {
  会: "can",
  能: "can",
  可以: "can",
};

export const DESIDERATIVE_TRANSLATIONS: Record<string, string> = {
  想: "want",
  要: "want",
};

export const RESULTATIVE_VERB_TRANSLATIONS: Record<string, string> = {
  看见: "see",
  看到: "see",
  找到: "find",
  学会: "learn",
  记住: "remember",
  听见: "hear",
  听懂: "understand",
  听到: "hear",
  看懂: "understand",
  做完: "finish",
  写完: "finish writing",
  买到: "buy",
  吃完: "finish eating",
  说完: "finish speaking",
};

export type ComplementMeaningCategory =
  | "ability"
  | "resultative"
  | "perception"
  | "comprehension"
  | "feasibility";

export type ComplementMeaning = {
  category: ComplementMeaningCategory;
  baseVerb: string;
  complement: string;
  positive: string;
  negative: string;
  object?: string;
  positiveQuestion?: string;
  negativeQuestion?: string;
};

export const COMPLEMENT_MEANINGS: Record<string, ComplementMeaning> = {
  看得懂: {
    category: "comprehension",
    baseVerb: "看",
    complement: "懂",
    positive: "can read and understand it",
    negative: "cannot understand it when reading it",
    object: "it",
    positiveQuestion: "read and understand it",
    negativeQuestion: "understand it when reading it",
  },
  看不懂: {
    category: "comprehension",
    baseVerb: "看",
    complement: "懂",
    positive: "can read and understand it",
    negative: "cannot understand it when reading it",
    object: "it",
    positiveQuestion: "read and understand it",
    negativeQuestion: "understand it when reading it",
  },
  听得见: {
    category: "perception",
    baseVerb: "听",
    complement: "见",
    positive: "can hear it",
    negative: "cannot hear it",
    object: "it",
    positiveQuestion: "hear it",
    negativeQuestion: "hear it",
  },
  听不见: {
    category: "perception",
    baseVerb: "听",
    complement: "见",
    positive: "can hear it",
    negative: "cannot hear it",
    object: "it",
    positiveQuestion: "hear it",
    negativeQuestion: "hear it",
  },
  听得懂: {
    category: "comprehension",
    baseVerb: "听",
    complement: "懂",
    positive: "can understand it when hearing it",
    negative: "cannot understand it when hearing it",
    object: "it",
    positiveQuestion: "understand it when hearing it",
    negativeQuestion: "understand it when hearing it",
  },
  听不懂: {
    category: "comprehension",
    baseVerb: "听",
    complement: "懂",
    positive: "can understand it when hearing it",
    negative: "cannot understand it when hearing it",
    object: "it",
    positiveQuestion: "understand it when hearing it",
    negativeQuestion: "understand it when hearing it",
  },
  找得到: {
    category: "ability",
    baseVerb: "找",
    complement: "到",
    positive: "can find it",
    negative: "cannot find it",
    object: "it",
    positiveQuestion: "find it",
    negativeQuestion: "find it",
  },
  找不到: {
    category: "ability",
    baseVerb: "找",
    complement: "到",
    positive: "can find it",
    negative: "cannot find it",
    object: "it",
    positiveQuestion: "find it",
    negativeQuestion: "find it",
  },
  做得到: {
    category: "ability",
    baseVerb: "做",
    complement: "到",
    positive: "can do it",
    negative: "cannot do it",
    object: "it",
    positiveQuestion: "do it",
    negativeQuestion: "do it",
  },
  做不到: {
    category: "ability",
    baseVerb: "做",
    complement: "到",
    positive: "can do it",
    negative: "cannot do it",
    object: "it",
    positiveQuestion: "do it",
    negativeQuestion: "do it",
  },
  办得到: {
    category: "ability",
    baseVerb: "办",
    complement: "到",
    positive: "can manage it",
    negative: "cannot manage it",
    object: "it",
    positiveQuestion: "manage it",
    negativeQuestion: "manage it",
  },
  办不到: {
    category: "ability",
    baseVerb: "办",
    complement: "到",
    positive: "can manage it",
    negative: "cannot manage it",
    object: "it",
    positiveQuestion: "manage it",
    negativeQuestion: "manage it",
  },
  学得会: {
    category: "ability",
    baseVerb: "学",
    complement: "会",
    positive: "can learn it",
    negative: "cannot learn it",
    object: "it",
    positiveQuestion: "learn it",
    negativeQuestion: "learn it",
  },
  学不会: {
    category: "ability",
    baseVerb: "学",
    complement: "会",
    positive: "can learn it",
    negative: "cannot learn it",
    object: "it",
    positiveQuestion: "learn it",
    negativeQuestion: "learn it",
  },
  记得住: {
    category: "ability",
    baseVerb: "记",
    complement: "住",
    positive: "can remember it",
    negative: "cannot remember it",
    object: "it",
    positiveQuestion: "remember it",
    negativeQuestion: "remember it",
  },
  记不住: {
    category: "ability",
    baseVerb: "记",
    complement: "住",
    positive: "can remember it",
    negative: "cannot remember it",
    object: "it",
    positiveQuestion: "remember it",
    negativeQuestion: "remember it",
  },
  打得开: {
    category: "ability",
    baseVerb: "打",
    complement: "开",
    positive: "can open it",
    negative: "cannot open it",
    object: "it",
    positiveQuestion: "open it",
    negativeQuestion: "open it",
  },
  打不开: {
    category: "ability",
    baseVerb: "打",
    complement: "开",
    positive: "can open it",
    negative: "cannot open it",
    object: "it",
    positiveQuestion: "open it",
    negativeQuestion: "open it",
  },
  来得及: {
    category: "feasibility",
    baseVerb: "来",
    complement: "及",
    positive: "can make it in time",
    negative: "cannot make it in time",
    object: "it",
    positiveQuestion: "make it in time",
    negativeQuestion: "make it in time",
  },
  来不及: {
    category: "feasibility",
    baseVerb: "来",
    complement: "及",
    positive: "can make it in time",
    negative: "cannot make it in time",
    object: "it",
    positiveQuestion: "make it in time",
    negativeQuestion: "make it in time",
  },
};

export const COMPLEMENT_TRANSLATIONS: Record<
  string,
  { positive?: string; negative?: string }
> = Object.fromEntries(
  Object.entries(COMPLEMENT_MEANINGS).map(([key, value]) => [
    key,
    {
      positive: key.includes("得") ? value.positive : undefined,
      negative: key.includes("不") ? value.negative : undefined,
    },
  ]),
);

export const DYNAMIC_PASSIVE_PARTICIPLES = new Set([
  "found",
  "caught",
  "seen",
  "hit",
  "hurt",
  "called",
  "invited",
  "stopped",
  "taken",
  "sent",
  "given",
]);

export const PROGRESSIVE_MARKERS = new Set(["在", "正在"]);

export const LEXICALIZED_EXPRESSION_TRANSLATIONS: Record<string, string> = {
  "你好": "Hello.",
  "您好": "Hello.",
  "你好吗": "How are you?",
  "您好吗": "How are you?",
  "你怎么样": "How are you?",
  "您怎么样": "How are you?",
  "最近怎么样": "How have you been lately?",
  "早上好": "Good morning.",
  "晚上好": "Good evening.",
  "晚安": "Good night.",
  "谢谢": "Thank you.",
  "不客气": "You're welcome.",
  "对不起": "I'm sorry.",
  "没关系": "It's okay.",
  "再见": "Goodbye.",
};

export const NEGATIVE_IMPERATIVE_MARKERS = new Set(["不要", "别"]);

export const IMPERATIVE_POLITENESS_MARKERS = new Set(["请"]);

export const IMPERATIVE_ADVERB_WORDS = new Set(["快"]);

export const SKIPPABLE_TOKENS = new Set([
  "的",
  "了",
  "过",
  "着",
  "吧",
  "呢",
  "啊",
  "呀",
  "啦",
]);

export const MEASURE_WORDS = new Set([
  "个",
  "本",
  "张",
  "只",
  "位",
  "条",
  "杯",
  "碗",
  "块",
  "件",
  "些",
]);

export const NUMBER_TRANSLATIONS: Record<string, string> = {
  一: "one",
  二: "two",
  两: "two",
  三: "three",
  四: "four",
  五: "five",
  六: "six",
  七: "seven",
  八: "eight",
  九: "nine",
  十: "ten",
};

export const NOUN_TRANSLATIONS: Record<string, string> = {
  人: "person",
  书: "book",
  门: "door",
  公司: "company",
  照片: "photo",
  饭: "meal",
  信: "letter",
  时间: "time",
  名字: "name",
  音乐: "music",
  问题: "question",
  事: "matter",
  事情: "matter",
  老师: "teacher",
  学生: "student",
};
